name: TestScripts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Download Issues With end limit
        id: normalIssuesWithEndLimitWindows
        shell: pwsh
        run: ./hackspace-downloader.ps1 -l 3
      - name: Download Issues with start and end limit
        id: normalIssuesWithStartAndEndRangeWindows
        shell: pwsh
        run: ./hackspace-downloader.ps1 -f 24 -l 25
      - name: Download Issues with start limit
        id: normalIssuesWithRangeAndStartLimitWindows
        shell: pwsh
        run: ./hackspace-downloader.ps1 -f 34
      - name: "Check file existence Windows"
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "issues/hackspace-magazine-issue-2.pdf, issues/hackspace-magazine-issue-25.pdf, issues/hackspace-magazine-issue-36.pdf"
          allow_failure: false
      - name: lslah
        run: Get-ChildItem issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1        
  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Download Issues with start limit Linux
        id: normalIssuesWithStartLimitLinux
        run: ./hackspace-downloader.sh -f 34
      - name: Download Issues with end limit Linux
        id: normalIssuesWithEndLimitLInux
        run: ./hackspace-downloader.sh -l 2
      - name: Download Issues with start and end limit Linux
        id: normalIssuesWithStartAndEndLimitLinux
        run: ./hackspace-downloader.sh -f 24 -l 25
      - name: download all books
        id: downloadallbooks
        run: ./hackspace-books-downloader.sh
      - name: "Check file existence linux"
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "issues/HackSpaceMag02.pdf, issues/HackSpaceMagazine25.pdf, issues/HackSpaceMagazine36.pdf, special-issues/Book_of_Making_v1.pdf, special-issues/Book_of_Making-vol2.pdf"
          allow_failure: false
      - name: lslah
        run: ls -lah . issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
  bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Download Issues with start limit Mac
        id: normalIssuesWithStartLimitMac
        run: ./hackspace-downloader.sh -f 34
      - name: Download Issues with start and end limit Mac
        id: normalIssuesWithEndLimitMac
        run: ./hackspace-downloader.sh -l 2
      - name: Download Issues with start and end limit Mac
        id: normalIssuesWithStartAndEndLimitMac
        run: ./hackspace-downloader.sh -f 24 -l 25
      - name: download all books
        id: downloadallbooks
        run: ./hackspace-books-downloader.sh
      - name: "Check file existence linux"
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "issues/HackSpaceMag02.pdf, issues/HackSpaceMagazine25.pdf, issues/HackSpaceMagazine36.pdf, special-issues/Book_of_Making_v1.pdf, special-issues/Book_of_Making-vol2.pdf"
          allow_failure: false
      - name: lslah
        run: ls -lah . issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
